# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CocoaPodsProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CocoaPodsProject
pod 'Alamofire', '~> 5.0.0-rc.1'

  target 'CocoaPodsProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
